trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install
  displayName: 'Install dependencies'

- script: npm run test:playwright
  displayName: 'Run Playwright tests'

- script: node lambdatest.js
  displayName: 'Run LambdaTest script'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Playwright Test Results'
    testRunSystem: 'Azure Pipelines'
